{'project_id': '3130', 'year': '1984', 'x': 1589160, 'y': 2212170, 'plot_id': '13836', 'strata': '41'}
Pandas(Index=0, project_id='3130', plot_id='13836', x=1589160, y=2212170)
called process_plot
Pandas(Index=0, project_id='3130', plot_id='13836', x=1589160, y=2212170)
13836
Directory '/efs/timesync/1984/audit/' already exists.
Data has been pickled and saved to '/efs/timesync/1984/audit/1984_13836_3130.p'.
............................Failed qa: 1984-05-21T15:25:48.3670500Z
.......Failed qa: 1984-06-06T15:26:09.9180250Z
..............Failed qa: 1984-06-22T15:26:25.2480810Z
Failed qa: 1984-07-08T15:26:35.2630880Z
.....................Failed qa: 1984-09-03T15:22:18.0870000Z
............................Failed qa: 1984-10-21T15:22:16.8010310Z
Failed qa: 1984-10-28T15:28:00.9310000Z
Failed qa: 1984-11-06T15:22:10.0120690Z
..............Data has been pickled and saved to '/efs/timesync/1984/audit/1984_13836_3130_qa_rejects.p'.
Success tracking goes here
