{'project_id': '3130', 'year': '1984', 'x': -2152380, 'y': 2484990, 'plot_id': '1766', 'strata': '41'}
Pandas(Index=0, project_id='3130', plot_id='1766', x=-2152380, y=2484990)
called process_plot
Pandas(Index=0, project_id='3130', plot_id='1766', x=-2152380, y=2484990)
1766
Directory '/efs/timesync/1984/audit/' already exists.
Data has been pickled and saved to '/efs/timesync/1984/audit/1984_1766_3130.p'.
.......Failed qa: 1984-05-07T18:30:35.099041Z
.......Failed qa: 1984-05-23T18:31:04.410091Z
.......Failed qa: 1984-06-08T18:31:13.2460560Z
..............Failed qa: 1984-06-24T18:31:39.618534Z
..............Failed qa: 1984-07-10T18:31:49.069028Z
.....................Failed qa: 1984-09-21T18:27:21.5800630Z
Failed qa: 1984-10-14T18:33:18.305085Z
..............Failed qa: 1984-12-01T18:33:20.9440000Z
Data has been pickled and saved to '/efs/timesync/1984/audit/1984_1766_3130_qa_rejects.p'.
Success tracking goes here
