{'project_id': '3130', 'year': '1984', 'x': -352350, 'y': 2782890, 'plot_id': '19176', 'strata': '41'}
Pandas(Index=0, project_id='3130', plot_id='19176', x=-352350, y=2782890)
called process_plot
Pandas(Index=0, project_id='3130', plot_id='19176', x=-352350, y=2782890)
19176
Directory '/efs/timesync/1984/audit/' already exists.
Data has been pickled and saved to '/efs/timesync/1984/audit/1984_19176_3130.p'.
Failed qa: 1984-03-22T17:06:07.2410000Z
Failed qa: 1984-04-10T17:08:27.439040Z
..............Failed qa: 1984-05-12T17:08:48.839522Z
..............Failed qa: 1984-05-28T17:09:15.521566Z
Failed qa: 1984-06-13T17:09:34.141547Z
..............Failed qa: 1984-06-29T17:09:46.960572Z
..............Failed qa: 1984-07-15T17:10:00.355544Z
...................................Failed qa: 1984-09-01T17:11:33.0640880Z
.....................Failed qa: 1984-10-03T17:11:24.091572Z
.......Failed qa: 1984-10-19T17:11:32.8290880Z
..............Failed qa: 1984-11-04T17:11:26.3000130Z
..............Failed qa: 1984-11-20T17:10:58.0030190Z
.......Data has been pickled and saved to '/efs/timesync/1984/audit/1984_19176_3130_qa_rejects.p'.
Success tracking goes here
