{'project_id': '3130', 'year': '1984', 'x': 552990, 'y': 2593260, 'plot_id': '20976', 'strata': '41'}
Pandas(Index=0, project_id='3130', plot_id='20976', x=552990, y=2593260)
called process_plot
Pandas(Index=0, project_id='3130', plot_id='20976', x=552990, y=2593260)
20976
Directory '/efs/timesync/1984/audit/' already exists.
Data has been pickled and saved to '/efs/timesync/1984/audit/1984_20976_3130.p'.
..............Failed qa: 1984-04-18T16:19:25.087522Z
..............Failed qa: 1984-05-04T16:19:29.750557Z
..............Failed qa: 1984-05-20T16:20:00.626009Z
..............Failed qa: 1984-06-05T16:20:10.9380810Z
Failed qa: 1984-06-07T16:07:51.5490630Z
.......Failed qa: 1984-06-21T16:20:38.495562Z
.......Failed qa: 1984-07-07T16:20:48.719043Z
..............Failed qa: 1984-07-23T16:21:03.1850560Z
Failed qa: 1984-08-01T16:15:11.2420750Z
Failed qa: 1984-08-08T16:21:48.072018Z
.....................Failed qa: 1984-09-27T16:09:48.2230560Z
...................................Failed qa: 1984-11-12T16:22:07.192510Z
.......Data has been pickled and saved to '/efs/timesync/1984/audit/1984_20976_3130_qa_rejects.p'.
Success tracking goes here
