{'project_id': '3130', 'year': '1984', 'x': 96270, 'y': 688350, 'plot_id': '14276', 'strata': '41'}
Pandas(Index=0, project_id='3130', plot_id='14276', x=96270, y=688350)
called process_plot
Pandas(Index=0, project_id='3130', plot_id='14276', x=96270, y=688350)
14276
Directory '/efs/timesync/1984/audit/' already exists.
Data has been pickled and saved to '/efs/timesync/1984/audit/1984_14276_3130.p'.
..............Failed qa: 1984-04-18T16:24:11.912040Z
Failed qa: 1984-05-20T16:24:47.378534Z
..............Failed qa: 1984-06-21T16:25:13.2580750Z
Failed qa: 1984-06-23T16:13:17.0370560Z
Failed qa: 1984-07-07T16:25:35.539075Z
.......Failed qa: 1984-08-26T16:14:53.3210000Z
Failed qa: 1984-09-09T16:27:06.949050Z
Failed qa: 1984-09-11T16:14:57.6470310Z
..............Failed qa: 1984-10-11T16:27:18.8310190Z
Failed qa: 1984-10-13T16:14:56.7550630Z
.......Failed qa: 1984-10-29T16:14:51.5070190Z
.......Failed qa: 1984-11-12T16:26:53.881056Z
.......Failed qa: 1984-11-28T16:26:55.406059Z
Data has been pickled and saved to '/efs/timesync/1984/audit/1984_14276_3130_qa_rejects.p'.
Success tracking goes here
