{'project_id': '3130', 'year': '1984', 'x': -1202070, 'y': 2131170, 'plot_id': '6651', 'strata': '41'}
Pandas(Index=0, project_id='3130', plot_id='6651', x=-1202070, y=2131170)
called process_plot
Pandas(Index=0, project_id='3130', plot_id='6651', x=-1202070, y=2131170)
6651
Directory '/efs/timesync/1984/audit/' already exists.
Data has been pickled and saved to '/efs/timesync/1984/audit/1984_6651_3130.p'.
Failed qa: 1984-03-15T17:22:51.335515Z
.......Failed qa: 1984-04-15T17:28:24.0950750Z
..............Failed qa: 1984-05-10T17:22:54.0170500Z
..............Failed qa: 1984-06-11T17:23:29.246553Z
..............Failed qa: 1984-06-27T17:23:42.784075Z
.......Failed qa: 1984-07-13T17:23:41.1350880Z
.......Failed qa: 1984-07-29T17:24:39.7130000Z
.......Failed qa: 1984-08-14T17:25:11.565047Z
Failed qa: 1984-09-15T17:25:32.922516Z
.......Failed qa: 1984-10-17T17:25:06.7460560Z
Failed qa: 1984-10-24T17:31:15.3640310Z
Failed qa: 1984-11-02T17:25:12.463062Z
Failed qa: 1984-11-09T17:31:07.6970000Z
Failed qa: 1984-11-18T17:25:06.666516Z
Data has been pickled and saved to '/efs/timesync/1984/audit/1984_6651_3130_qa_rejects.p'.
Success tracking goes here
