{'project_id': '3130', 'year': '1984', 'x': -679050, 'y': 2884260, 'plot_id': '14896', 'strata': '41'}
Pandas(Index=0, project_id='3130', plot_id='14896', x=-679050, y=2884260)
called process_plot
Pandas(Index=0, project_id='3130', plot_id='14896', x=-679050, y=2884260)
14896
Directory '/efs/timesync/1984/audit/' already exists.
Data has been pickled and saved to '/efs/timesync/1984/audit/1984_14896_3130.p'.
..............Failed qa: 1984-05-01T17:26:46.6930750Z
.....................Failed qa: 1984-06-02T17:27:42.4980630Z
.......Failed qa: 1984-06-18T17:27:59.2730060Z
..............Failed qa: 1984-07-04T17:28:10.4620630Z
..............Failed qa: 1984-07-20T17:28:31.9560130Z
..............Failed qa: 1984-08-05T17:29:05.4980440Z
..............Failed qa: 1984-08-21T17:29:35.8630750Z
.....................Failed qa: 1984-10-08T17:29:43.9430630Z
.....................Data has been pickled and saved to '/efs/timesync/1984/audit/1984_14896_3130_qa_rejects.p'.
Success tracking goes here
