{'project_id': '3130', 'year': '1984', 'x': 1164780, 'y': 1563810, 'plot_id': '20941', 'strata': '41'}
Pandas(Index=0, project_id='3130', plot_id='20941', x=1164780, y=1563810)
called process_plot
Pandas(Index=0, project_id='3130', plot_id='20941', x=1164780, y=1563810)
20941
Directory '/efs/timesync/1984/audit/' already exists.
Data has been pickled and saved to '/efs/timesync/1984/audit/1984_20941_3130.p'.
Failed qa: 1984-03-15T15:45:21.6740000Z
.......Failed qa: 1984-04-08T15:45:18.3210060Z
.......Failed qa: 1984-04-24T15:45:06.349547Z
............................Failed qa: 1984-06-11T15:46:11.474050Z
..............Failed qa: 1984-06-27T15:46:25.042566Z
.......Failed qa: 1984-07-13T15:46:35.105540Z
.......Failed qa: 1984-07-29T15:47:09.922069Z
.......Failed qa: 1984-09-08T15:41:51.363072Z
.......Failed qa: 1984-09-24T15:41:53.093518Z
Failed qa: 1984-10-01T15:47:51.7140690Z
..............Failed qa: 1984-10-17T15:48:12.8430630Z
............................Data has been pickled and saved to '/efs/timesync/1984/audit/1984_20941_3130_qa_rejects.p'.
Success tracking goes here
