{'project_id': '1211', 'year': '1989', 'x': -1425390, 'y': 1267980, 'plot_id': '1805', 'strata': '41'}
Pandas(Index=0, project_id='1211', plot_id='1805', x=-1425390, y=1267980)
called process_plot
Pandas(Index=0, project_id='1211', plot_id='1805', x=-1425390, y=1267980)
1805
Directory '/efs/timesync/1989/audit/' already exists.
Data has been pickled and saved to '/efs/timesync/1989/audit/1989_1805_1211.p'.
............................Failed qa: 1989-04-13T17:32:55.202566Z
.......Failed qa: 1989-04-29T17:32:36.014547Z
.......Failed qa: 1989-05-15T17:32:18.953031Z
.......Failed qa: 1989-05-31T17:32:06.429034Z
...................................Failed qa: 1989-07-02T17:31:27.645034Z
.......Failed qa: 1989-07-18T17:31:06.964584Z
.......Failed qa: 1989-08-03T17:30:47.032594Z
..............Failed qa: 1989-08-19T17:30:24.078066Z
..............Failed qa: 1989-09-04T17:30:05.140541Z
...................................Failed qa: 1989-10-06T17:29:23.227553Z
..............Failed qa: 1989-11-07T17:28:22.354544Z
Data has been pickled and saved to '/efs/timesync/1989/audit/1989_1805_1211_qa_rejects.p'.
Success tracking goes here
