{'project_id': '1211', 'year': '1989', 'x': -2137440, 'y': 2808450, 'plot_id': '3772', 'strata': '41'}
Pandas(Index=0, project_id='1211', plot_id='3772', x=-2137440, y=2808450)
called process_plot
Pandas(Index=0, project_id='1211', plot_id='3772', x=-2137440, y=2808450)
3772
Directory '/efs/timesync/1989/audit/' already exists.
Data has been pickled and saved to '/efs/timesync/1989/audit/1989_3772_1211.p'.
.......Failed qa: 1989-04-03T18:31:43.0440500Z
.......................................................................................................................Data has been pickled and saved to '/efs/timesync/1989/audit/1989_3772_1211_qa_rejects.p'.
Success tracking goes here
