{'project_id': '1211', 'year': '1989', 'x': 1299690, 'y': 1660890, 'plot_id': '2325', 'strata': '41'}
Pandas(Index=0, project_id='1211', plot_id='2325', x=1299690, y=1660890)
called process_plot
Pandas(Index=0, project_id='1211', plot_id='2325', x=1299690, y=1660890)
2325
Directory '/efs/timesync/1989/audit/' already exists.
Data has been pickled and saved to '/efs/timesync/1989/audit/1989_2325_1211.p'.
............................Failed qa: 1989-02-03T15:35:49.6800310Z
............................Failed qa: 1989-04-17T15:28:36.8670130Z
..............Failed qa: 1989-05-10T15:34:25.2410380Z
............................Failed qa: 1989-06-20T15:27:24.6130000Z
Failed qa: 1989-07-06T15:27:08.9810630Z
.....................Failed qa: 1989-08-14T15:32:30.2000130Z
Failed qa: 1989-08-23T15:26:08.1520190Z
..............Failed qa: 1989-09-15T15:31:35.8500500Z
...................................Data has been pickled and saved to '/efs/timesync/1989/audit/1989_2325_1211_qa_rejects.p'.
Success tracking goes here
