{'project_id': '1211', 'year': '1989', 'x': 550050, 'y': 1130310, 'plot_id': '1185', 'strata': '41'}
Pandas(Index=0, project_id='1211', plot_id='1185', x=550050, y=1130310)
called process_plot
Pandas(Index=0, project_id='1211', plot_id='1185', x=550050, y=1130310)
1185
Directory '/efs/timesync/1989/audit/' already exists.
Data has been pickled and saved to '/efs/timesync/1989/audit/1989_1185_1211.p'.
Failed qa: 1989-01-05T16:08:11.3640130Z
.......Failed qa: 1989-01-28T16:13:15.2530310Z
............................Failed qa: 1989-03-17T16:12:33.710528Z
..............Failed qa: 1989-04-04T16:00:48.4300130Z
........................................................Failed qa: 1989-06-30T16:05:34.4230940Z
.......Failed qa: 1989-07-16T16:04:50.109040Z
.......Failed qa: 1989-08-01T16:04:30.749041Z
.................................................Data has been pickled and saved to '/efs/timesync/1989/audit/1989_1185_1211_qa_rejects.p'.
Success tracking goes here
