{'project_id': '1211', 'year': '1989', 'x': -206190, 'y': 2578650, 'plot_id': '4016', 'strata': '41'}
Pandas(Index=0, project_id='1211', plot_id='4016', x=-206190, y=2578650)
called process_plot
Pandas(Index=0, project_id='1211', plot_id='4016', x=-206190, y=2578650)
4016
Directory '/efs/timesync/1989/audit/' already exists.
Data has been pickled and saved to '/efs/timesync/1989/audit/1989_4016_1211.p'.
.....................Failed qa: 1989-03-25T16:58:28.0790130Z
.......Failed qa: 1989-04-10T16:58:28.467525Z
.....................Failed qa: 1989-04-28T16:45:33.6810250Z
.....................Failed qa: 1989-05-28T16:57:40.069522Z
Failed qa: 1989-05-30T16:45:04.7760750Z
.....................Failed qa: 1989-07-07T17:02:48.361041Z
.......Failed qa: 1989-07-15T16:56:41.985553Z
..............Failed qa: 1989-07-31T16:56:22.931053Z
..............Failed qa: 1989-08-16T16:55:58.369540Z
.......Failed qa: 1989-09-01T16:55:40.154081Z
.......Failed qa: 1989-09-10T16:48:59.9480000Z
Failed qa: 1989-09-17T16:55:07.271065Z
..............Failed qa: 1989-10-03T16:54:58.962076Z
.......Failed qa: 1989-10-28T16:47:40.7070500Z
Failed qa: 1989-11-06T16:41:22.4360630Z
Data has been pickled and saved to '/efs/timesync/1989/audit/1989_4016_1211_qa_rejects.p'.
Success tracking goes here
