{'project_id': '1211', 'year': '1989', 'x': 78270, 'y': 2138220, 'plot_id': '3781', 'strata': '41'}
Pandas(Index=0, project_id='1211', plot_id='3781', x=78270, y=2138220)
called process_plot
Pandas(Index=0, project_id='1211', plot_id='3781', x=78270, y=2138220)
3781
Directory '/efs/timesync/1989/audit/' already exists.
Data has been pickled and saved to '/efs/timesync/1989/audit/1989_3781_1211.p'.
.......Failed qa: 1989-01-15T16:41:53.9860440Z
.......Failed qa: 1989-01-31T16:41:48.6010130Z
.......Failed qa: 1989-02-16T16:41:45.5710310Z
..............Failed qa: 1989-03-20T16:40:48.7210810Z
.......Failed qa: 1989-04-05T16:40:54.4730940Z
Failed qa: 1989-04-07T16:28:33.9640630Z
Failed qa: 1989-04-21T16:40:40.1420690Z
..............Failed qa: 1989-05-07T16:40:29.3020000Z
..........................................Failed qa: 1989-07-10T16:39:15.6010500Z
.......Failed qa: 1989-07-26T16:38:56.5700940Z
.....................Failed qa: 1989-08-11T16:38:34.3510940Z
Failed qa: 1989-08-12T16:39:06.0750630Z
.....................Failed qa: 1989-09-12T16:37:43.5620310Z
.....................Failed qa: 1989-10-14T16:36:58.1570440Z
............................Failed qa: 1989-12-01T16:35:38.7600560Z
Data has been pickled and saved to '/efs/timesync/1989/audit/1989_3781_1211_qa_rejects.p'.
Success tracking goes here
