{'project_id': '1211', 'year': '1989', 'x': 1351110, 'y': 1466400, 'plot_id': '2686', 'strata': '41'}
Pandas(Index=0, project_id='1211', plot_id='2686', x=1351110, y=1466400)
called process_plot
Pandas(Index=0, project_id='1211', plot_id='2686', x=1351110, y=1466400)
2686
Directory '/efs/timesync/1989/audit/' already exists.
Data has been pickled and saved to '/efs/timesync/1989/audit/1989_2686_1211.p'.
Failed qa: 1989-01-04T15:23:56.160038Z
.......Failed qa: 1989-01-20T15:23:24.3640310Z
..............Failed qa: 1989-03-09T15:22:56.6100250Z
.......Failed qa: 1989-03-25T15:22:33.812550Z
.......Failed qa: 1989-04-26T15:22:26.551072Z
.......Failed qa: 1989-05-12T15:22:11.761028Z
.......Failed qa: 1989-05-28T15:21:58.006066Z
.......Failed qa: 1989-06-13T15:21:34.572012Z
.......Failed qa: 1989-06-29T15:21:20.066579Z
..............Failed qa: 1989-07-31T15:20:40.770540Z
.......Failed qa: 1989-08-16T15:20:16.352057Z
.......Failed qa: 1989-09-01T15:19:58.226553Z
.......Failed qa: 1989-09-17T15:19:25.194056Z
.......Failed qa: 1989-10-03T15:19:16.922547Z
.....................Failed qa: 1989-11-20T15:17:35.401541Z
Data has been pickled and saved to '/efs/timesync/1989/audit/1989_2686_1211_qa_rejects.p'.
Success tracking goes here
