{'project_id': '1211', 'year': '1989', 'x': -2025210, 'y': 2486040, 'plot_id': '4940', 'strata': '41'}
Pandas(Index=0, project_id='1211', plot_id='4940', x=-2025210, y=2486040)
called process_plot
Pandas(Index=0, project_id='1211', plot_id='4940', x=-2025210, y=2486040)
4940
Directory '/efs/timesync/1989/audit/' already exists.
Data has been pickled and saved to '/efs/timesync/1989/audit/1989_4940_1211.p'.
........................................................Failed qa: 1989-04-12T18:25:58.4580880Z
.......Failed qa: 1989-04-28T18:25:38.3620060Z
..............Failed qa: 1989-05-14T18:25:22.6540250Z
...................................Failed qa: 1989-06-15T18:24:41.5520630Z
.....................Failed qa: 1989-07-01T18:24:31.1710250Z
.....................Failed qa: 1989-07-17T18:24:10.6130000Z
.....................Failed qa: 1989-08-02T18:23:50.9370060Z
..............Failed qa: 1989-08-18T18:23:26.9410690Z
.......Failed qa: 1989-09-03T18:23:08.7200500Z
..............Failed qa: 1989-09-19T18:22:36.7230630Z
..............Failed qa: 1989-10-05T18:22:27.2440690Z
.....................Failed qa: 1989-11-06T18:21:26.9460630Z
.......Failed qa: 1989-11-22T18:20:48.7900440Z
.......Data has been pickled and saved to '/efs/timesync/1989/audit/1989_4940_1211_qa_rejects.p'.
Success tracking goes here
