{'project_id': '1211', 'year': '1989', 'x': 987360, 'y': 1312500, 'plot_id': '964', 'strata': '41'}
Pandas(Index=0, project_id='1211', plot_id='964', x=987360, y=1312500)
called process_plot
Pandas(Index=0, project_id='1211', plot_id='964', x=987360, y=1312500)
964
Directory '/efs/timesync/1989/audit/' already exists.
Data has been pickled and saved to '/efs/timesync/1989/audit/1989_0964_1211.p'.
.....................................................................................................................................Failed qa: 1989-09-22T15:38:29.4170000Z
...................................Data has been pickled and saved to '/efs/timesync/1989/audit/1989_0964_1211_qa_rejects.p'.
Success tracking goes here
