{'project_id': '1211', 'year': '1989', 'x': 1316610, 'y': 1093200, 'plot_id': '2158', 'strata': '41'}
Pandas(Index=0, project_id='1211', plot_id='2158', x=1316610, y=1093200)
called process_plot
Pandas(Index=0, project_id='1211', plot_id='2158', x=1316610, y=1093200)
2158
Directory '/efs/timesync/1989/audit/' already exists.
Data has been pickled and saved to '/efs/timesync/1989/audit/1989_2158_1211.p'.
Failed qa: 1989-01-02T15:37:05.949028Z
Failed qa: 1989-01-18T15:36:48.746060Z
.......Failed qa: 1989-02-03T15:36:49.450041Z
.....................Failed qa: 1989-04-08T15:35:56.027559Z
.......Failed qa: 1989-04-24T15:35:38.136057Z
.......Failed qa: 1989-05-10T15:35:25.029572Z
.......Failed qa: 1989-05-26T15:35:08.649053Z
.......Failed qa: 1989-06-11T15:34:49.058063Z
.....................Failed qa: 1989-07-29T15:33:52.767041Z
.......Failed qa: 1989-08-14T15:33:29.868006Z
.......Failed qa: 1989-08-30T15:33:10.304037Z
.......Failed qa: 1989-09-15T15:32:35.597047Z
Failed qa: 1989-09-24T15:26:07.9720630Z
Failed qa: 1989-10-10T15:25:48.2000130Z
Failed qa: 1989-10-17T15:32:01.0760000Z
Failed qa: 1989-10-26T15:25:07.2510560Z
.......Failed qa: 1989-11-18T15:30:39.1060940Z
Data has been pickled and saved to '/efs/timesync/1989/audit/1989_2158_1211_qa_rejects.p'.
Success tracking goes here
